#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/apt-add-key
# 

KEY=${1}

if [ -z "${KEY//[^a-fA-F0-9]/}" ]
then
	echo "apt-add-key [keysig]"
else
	apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ${KEY//[^a-fA-F0-9]/}
fi
