#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/confdiff
# 

F1=$1
F2=$2

if [ -r "${F1}" -a -r "${F2}" ]
then
	diff -u  <(grep -vE '^[[:space:]]*#|^[[:space:]]*$' "${F1}")  <(grep -vE '^[[:space:]]*#|^[[:space:]]*$' "${F2}") | \
		sed "s/^\(---[\t ]\+\)\(.*\)\([\t ]\+[0-9]\{4\}-\)/\1${F1}\3/; s/^\(+++[\t ]\+\)\(.*\)\([\t ]\+[0-9]\{4\}-\)/\1${F2}\3/;"

else
	echo "confdiff [file1] [file2]"
fi
