#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/cwdiff
# 
F1=$1
F2=$2
if [ -z "$F1" -o -z "$F2" ]
then
   echo "usage:   cwdiff [file1] [file2]"
   echo "   word-colored differences between two files"
   exit 1
fi

git diff --color-words --word-diff "$F1" "$F2"
