#!/bin/bash
for module in $(dkms status | sed 's/, /\//g; s/:.*//g' | cut -f 1-2 -d/)
do
    for VER in $(ls -1 /boot/vmlinuz-* | cut -f2- -d-)
    do
	echo "Working on ${module} for ${VER}"
	dkms build $module -k ${VER} && dkms install $module -k ${VER} || break
    done
done
