#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/gen-strong-pw
# 
PROG="${0##*/}"
MIN=5
WORDS=40
COLUMNS=$(stty size | awk '{print $2}')

cleanup() {
	if [ -e "${TFILE}" ]
	then
		rm -f "${TFILE}"
	fi
}

usage() {
	echo "${PROG} [-l #] [-w #] [-D path] [-d file] -f"
	echo ""
	echo "generates a random word list with optional minimum-character-length words:"
	echo "  -w #       # display '#' (default: ${WORDS}) words in the selector"
	echo "  -l #       # use a minimum word length (default: ${MIN})"
	echo "  -D path    # use path for dictionary location (all files sourced)"
	echo "  -d file    # use file  as the single-source dictionary"
	echo "  -f         # force usage of filespec, even if less than optimal wordcount"
	echo ""
	exit
}

while getopts ":fl:w:d:D:" param; do
 case $param in
  l) MIN=$OPTARG ;;
  w) WORDS=$OPTARG ;;
  D) DPATH=$OPTARG ;;
  d) DFILE=$OPTARG ;;
  f) FORCE=1 ;;
  *) usage ;;
 esac
done

# only numbers, please.
if [ -n "${MIN//[0-9]/}" ];
then
        usage
fi
if [ -n "${WORDS//[0-9]/}" ];
then
        usage
fi

if [ -n "${DPATH}" -a ! -d "${DPATH}" ]
then
	echo "${DPATH} is not a directory"
	usage
elif [ -n "${DPATH}" -a -n "${DFILE}" ]
then
	echo "cannot use both -D  and -d  simulataneously"
	usage
fi
if [ -n "${DFILE}" -a ! -r "${DFILE}" ]
then
	echo "${DFILE} is not a regular file, or cannot read"
	usage
fi

TFILE=$(mktemp /tmp/${PROG}.XXXXXXX)

echo "${PROG}:"
echo -e "\tChoose a few words (at least three! preferably five or more), capitalize one, combine, add punctuation, and you're done"
echo -e "\t(try combining the words with a space or additional punctuation)"
echo -e "\tex:"
echo -e "\t\tDispassionate-moustache!\t\tjazzier-velour?terminals\t\tpathologically_sugarier>burglarising*promoters"
echo ""

echo "Generating..."

if [ -n "${DPATH}" ]
then
	DSPEC="$(ls ${DPATH}/*)"
elif [ -n "${DFILE}" ]
then
	DSPEC=${DFILE}
else
	DSPEC="$(ls /usr/share/dict/*)"
fi
grep -wE --no-filename "[a-z]{$MIN,}" ${DSPEC} 2>/dev/null | grep -Ev "'s|[^ -~]" | tr [A-Z] [a-z] | sort -u > "${TFILE}"
lines=$( wc -l "${TFILE}" | awk '{print $1}' )

if [ ${lines:-0} -lt 4000 -a ${FORCE:-0} -ne 1 ]
then
	echo "*** WARNING ***"
	echo "   You do not have enough word-lists to provide a secure token-space"
	echo "   Download and install additional dictionaries into /usr/share/dict/"
	echo "*** WARNING ***"
fi

echo -e "\nRandom words to generate pass-phrases from a combined ${lines} words, of min-length ${MIN}:"

echo ""
echo $(sort --random-sort "${TFILE}" | head -${WORDS} ) | fold --width=$(( COLUMNS - (COLUMNS * 100 /275) )) -s | column -s" " -t
echo ""

cleanup
