#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/git-updates
# 
CWD=$(pwd)
PROG="${0##*/}"

trap cleanup SIGINT SIGTERM SIGKILL SIGQUIT SIGABRT SIGSTOP SIGSEGV

cleanup() {
	echo -e "\n\n"
	exit 0
}

usage() {
	echo "Usage:"
	echo "${PROG} [-c] [-h] [-d N]"
	echo ""
	echo "    by default, recursively scans for git/git-svn repos and pulls updates"
	echo ""
	echo "    -c  'check' - will only show repos that have pending changes"
	echo "    -dN 'depth' - will change the default scanning depth from 3 to N"
	echo "    -h  'help'  - this usage text"

	cleanup
}

while getopts ':chd:' opt; do
  case $opt in
    c) CHECK=1
      ;;
    h) usage
      ;;
    d) DEPTH="${OPTARG//[^0-9]/}"
      ;;
    *) echo "Invalid option: -$OPTARG"
       usage
      ;;
  esac
done

for DIR in $(find . -maxdepth ${DEPTH:-3}  -type d -iname .git -o -iname .hg )
do
	# echo ./proxyapp/.git | cut -f 2 -d/
	SUBDIR=${DIR:2}

	if [ -z "${SUBDIR##*.git*}" ]
	then
		SUBDIR=${SUBDIR//\/.git}

		if [ -d "${SUBDIR}/.git/svn/refs" ];
		then
			echo -n "checking git-svn repo ${SUBDIR}: "
			cd ${SUBDIR}
			if [ ${CHECK:-0} -eq 1 ]
			then
				git diff --quiet
				test $? -eq 1 && echo "git-svn repo ${SUBDIR} has pending changes"
			else
				git svn fetch
			fi
		elif [ -e "${SUBDIR}/.git/config" -a -n "$(grep -w url ${SUBDIR}/.git/config)" ]
		then
			cd ${SUBDIR}
			if [ ${CHECK:-0} -eq 1 ]
			then
				git diff --quiet
				test $? -eq 1 && echo "git repo ${SUBDIR} has pending changes"
			else
				echo -n "checking git repo ${SUBDIR}: "
				git pull --recurse
			fi
		fi
		cd ${CWD}
	elif [ -z "${SUBDIR##*.hg*}" ]
	then
		SUBDIR=${SUBDIR//\/.hg}
		if [ -e "${SUBDIR}/.hg/hgrc" -a -n "$(grep -w default ${SUBDIR}/.hg/hgrc)" ]
		then
			cd ${SUBDIR}
			if [ ${CHECK:-0} -eq 1 ]
			then
				hg update --check >/dev/null 2>&1
				test $? -eq 1 && echo "mercurial repo ${SUBDIR} has pending changes"
			else
				echo -n "checking mercurial repo ${SUBDIR}: "
				hg update
			fi
			cd ${CWD}
		fi
	fi
done
