#!/bin/bash
CWD=$(pwd)
for DIR in $(find . -maxdepth 3  -type d -iname .git)
do
	# echo ./proxyapp/.git | cut -f 2 -d/
	SUBDIR=${DIR:2}
	SUBDIR=${SUBDIR//\/.git}

	if [ -d "${SUBDIR}/.git/svn/refs" ];
	then
		echo -n "checking git-svn repo ${SUBDIR}: "
		cd ${SUBDIR} && git svn fetch
		cd ${CWD}
	elif [ -e "${SUBDIR}/.git/config" -a -n "$(grep -w url ${SUBDIR}/.git/config)" ]
	then
		echo -n "checking git repo ${SUBDIR}: "
		cd ${SUBDIR} && git pull
		cd ${CWD}
	fi
done
