#!/bin/bash
# (c) 2023 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/hex2ascii
# 

##  This will read from stdin and print to stdout
##  converting a pair of hex digits to the ascii equivalent.
hexprint()
{
	l=${1// /}		# no spaces
	l=${l,,}		# lowercase
	l=${l//[^0-9a-f]/}	# only hex

	s=$(echo $l | sed 's/\(..\)/\1 /g')	# add a space between each pair of hex digits

	for h in ${s}
	do
		printf "\x${h}"
	done
	printf "\n"
}

if [ -z "$*" ]
then
	while read line
	do
		hexprint "${line}"
	done
else
	hexprint "$*"
fi

