#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/ip6tables-watch
# 
FILTER=""

if [ -n "${1}" ];
then
        case ${1} in
                nat) FILTER="-t nat"
                        ;;
                mangle) FILTER="-t mangle"
                        ;;
                filter) FILTER="-t filter"
                        ;;
                *) echo "$0 [nat|mangle|filter]"; exit 1
                        ;;
        esac
fi

watch -n1 -d "ip6tables -vnxL ${FILTER} | grep -v -e pkts -e Chain | sort -nk1 | tac | column -t"
