#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/jmake
# 
PROG="${0##*/}"
CPUS=$(grep -c "^processor" /proc/cpuinfo )

CPUS=$(($CPUS * 3 / 2))

if [ $CPUS -gt 4 ]
then
        CPUS="-j $CPUS"
else
        CPUS=""
fi

DO_RETURN=${SHLVL}

do_exit()
{
        STATUS=${1:-0}

        if [ ${DO_RETURN} -eq 1 ];
        then
                return $STATUS
        else
                exit $STATUS
        fi
}

make ${CPUS}
