#!/bin/bash

usage() {
  echo "$(cd $HOME/jnlps/; ls *.jnlp | sed 's/\.jnlp//g')"
  exit 1
}

if [ -z "$1" ]
then
  echo "which java webstart pacakge?"
  usage
else
	JNLP=${1}
fi

JNLP=${JNLP//.jnlp/}
JNLP=${JNLP//.jws/}

if [ -e "$HOME/jnlps/${JNLP}.jnlp" ]
then
    JWS="$HOME/jnlps/${JNLP}.jnlp"
elif [ -e "$HOME/jnlps/${JNLP}.jws" ]
then
    JWS="$HOME/jnlps/${JNLP}.jws"
elif [ -e "${1}" ]
then
    JWS="${1}"
else
  echo "invalid java webstart package ${JNLP}"
  usage
fi

# use one or more of these to work around java swing display corruption
#    -Dsun.java2d.opengl=true
#    -Dsun.java2d.d3d=false
#    -Dsun.java2d.noddraw=true


#/usr/lib/jvm/java-7-oracle/jre/bin/
if [ -e "${HOME}/jnlps/javaws" ]
then
	JWX="${HOME}/jnlps/javaws"
else
	JWX="javaws"	# system
fi
${JWX} -J"-Dsun.java2d.d3d=false" -Xnosplash -wait "${JWS}"
