#!/bin/bash
# reads a list of MD5sums and filenames and outputs only the duplicates
#
# you could feed it with something like:
#    find Pictures/ -type f -print0 | xargs -0 -i md5sum "{}" > allmd5s
# and then
#    md5dups < allmd5s
#
# We use a long second fieldwidth to get around spaces in filenames/paths for the second argument
#
# alias findups='find . -type f -links 1 -print0 | xargs -0 -i md5sum "{}" | md5dups'
awk '
	BEGIN { 
		FIELDWIDTHS = "32 256";
	};

        $1 != /^$/ {
                md5=$1
                fname=$2
		files[fname]=md5
		hashes[md5]=hashes[md5] + 1
        };
  
        END {
		for (md5 in hashes) {
			if (hashes[md5] > 1) {
				for (fname in files) {
					if ( files[fname] == md5 ) {
						print md5 " " fname;
					}
				}
			}
		}
        };
        '

# end
