#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/oclhcbench
# 

MODES=(0 100 500 1000 1400 1500 1700 1800 2500 3000 3200 5500 5600 6211 6800 7100 7500 11300 11600 12500 13000 13100 13400 15300 15900 18100 18900)
#
# You can easily parse and import using:
#
#  $ oclhcbench | oclhcbench2csv > oclhcbench.csv
#


if [ -n "$1" -a "${1}" = "single" ]
then
	ONEHIT=1
elif [ -n "$1" -a "${1}" = "group" ]
then
	GROUP=1
else
	GROUP=0
	ONEHIT=0
fi

tmpfile=$(mktemp)
hashcat -I 2>&1 > ${tmpfile}

declare -A devices
plid=0
did=0
idx=0

while read line
do
  if [ -n "${line}" -a -z "${line##Platform ID*}" ]
  then
    plid=${line//Platform ID #/}
  elif [ -n "${line}" -a -z "${line##OpenCL Platform ID*}" ]
  then
    plid=${line//OpenCL Platform ID #/}
    
  else

    # Backend Device ID #2 (Alias: #1)
   #or
    # Backend Device ID #3
   #or
    #   Device ID #2

    if [ -n "${line}" -a -z "${line##*Device ID*}" ]
    then
      did=${line//*Device ID #/}
      did=${did// */}
      idx="${plid}-${did}"
      devices[$idx]=1
    fi
  fi
done < "${tmpfile}"

echo "finished parsing OCL devices"
rm -f "${tmpfile}"

if [ ${GROUP:-0} -eq 0 ]
then
  for key in "${!devices[@]}"
  do
    if [ ${devices[$key]} -eq 1 ]
    then
      didx=${key#*-}
      dtype=${key%-*}

      PLAT="-D 1,2"
      if [ ${ONEHIT} -eq 0 ];
      then
        hashcat --workload-profile=4 --force ${PLAT} -d ${didx} --benchmark 2>&1
      else
        for idx in "${!MODES[@]}"
        do
          hashcat --workload-profile=4 --force ${PLAT} -d ${didx} --benchmark -m ${MODES[$idx]} 2>&1
        done
      fi
    fi
  done
else
  for idx in "${!MODES[@]}"
  do
    hashcat --workload-profile=4 --force --opencl-device-types=1,2,3 --benchmark -m ${MODES[$idx]} 2>&1
  done
fi
