#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/pmaptitude
# 
#  PMaptitude - pacman-interface from aptitude
#
#  super insecure.  Don't use this on multi-user systems.
#  really, just don't use this
#
PROG=${0##*/}
CMD="$1"
shift

ARGS="${*}"
# some very basic, not at all effective, sanitizing
ARGS="${ARGS//[\'\`\$\(\)]/}"

if [ -n "${ARGS}" ]
then
	if [ -z "${ARGS##*--no-install-recommends*}" ]
	then
		ARGS=${ARGS//--no-install-recommends/}
		OPTS="${OPTS} --asexplicit"
	fi
	if [ -z "${ARGS##*--dry-run*}" ]
	then
		ARGS=${ARGS//--dry-run/}
		OPTS="${OPTS} --print"
	fi
	if [ -z "${ARGS##*-y*}" ]
	then
		ARGS=${ARGS//-y/}
		OPTS="${OPTS} --noconfirm"
	fi
fi

case "$CMD" in
	find) pacman -F ${OPTS} ${ARGS}
		;;
	search) pacman -Ss ${OPTS} ${ARGS// /|}
		;;
	install) pacman -S ${OPTS} ${ARGS}
		;;
	update) pacman -Syy
		;;
	upgrade|dist-upgrade) pacman -Syu ${OPTS} ${ARGS}
		;;
	remove|purge) pacman -Rs ${OPTS} ${ARGS}
		;;
	clean|autoclean) pacman -Sc
		;;
	autoremove) pacman -Qdtq | pacman -Rs -
		;;
	show) pacman -Si ${OPTS} ${ARGS}
		;;
	*) echo "ERR: null or unsupported apt command for pacman: ${CMD}"
	   echo "USAGE:"
	   echo "    $PROG [find|search|install|remove|purge|show] {pkgspec}"
	   echo "             [update|upgrade|dist-upgrade|clean|autoclean|autoremove]"	
		;;
esac
