#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/rsync-cp
# 
PROG="${0##*/}"

usage() {
	echo -e "${PROG} - copy files using rsync\n"
	echo -e "usage:\n\$ ${PROG} (options) [src] [dst]"
	echo -e "\t-d, --dryrun\t\t Dry-run test, don't copy any files"
	echo -e "\t-h, --help\t\t this help.\n"
	exit 1
}

optspec=":dih-"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        -)
            case "${OPTARG}" in
                help)
                    usage
                    ;;
                dryrun)
                    DRY=1 
                    ;;
                ignore-existing|ignoreexisting)
                    MARGS="--ignore-existing"
                    ;;
                *)
                    if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
                        echo "Unknown option --${OPTARG}" >&2
                    fi
                    ;;
            esac;;
        d)
            DRY=1
            ;;
        h)
            usage
            ;;
        i)
            MARGS="--ignore-existing"
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
    esac
done

if [ 1 -lt ${OPTIND} ]
then
	src="${!OPTIND}"
	shift "$((OPTIND-1))"
	dst="${!OPTIND}"
else
	src=$1
	dst=$2
fi

if [ \( ! -d "${src}" -a ! -z "${src##*:*}" \) -a \( ! -d "${dst}" -a ! -z "${dst##*:*}" \) ]
then
	echo "ERROR in file specification"
	usage
else
        ionice nice rsync -avxWAXSH ${MARGS} ${DRY:+--dry-run} --numeric-ids --info=progress2 "${src}" "${dst}"

# -a  : all files, with permissions, etc..
# -v  : verbose, mention files
# -x  : stay on one file system
# -W  : whole files (not delta changes)
# -A  : preserve ACLs/permissions (not included with -a)
# -X  : preserve extended attributes (not included with -a)
# -H  : preserve hard links (not included with -a)
# -S  : Sparse file support
# --info=progress2 : only show grand total of progress
# --numeric-ids : just transfer uid/gid, don't map names


fi
