#!/bin/bash

usage() {

	echo "usage:  sddd infile outfile [blocksize]"
	echo "        synchronicely writes infile to outfile using dd"
}

if [ -z "${1}" -o -z "${2}" ];
then
	usage
	exit 1
fi

INFILE="$1"
OUTFILE="$2"
BS=${3//[^0-9]/}
BS=${BS:-512}

if [ ! -r "${INFILE}" ];
then
	echo "Can't read from ${INFILE}, bailing out"
	exit 1
fi

if [ ! -e "${OUTFILE}" -a ! -w "${OUTFILE}" ];
then
	echo "Can't write to ${OUTFILE}, bailing out"
	exit 1
fi

echo "copying from ${INFILE} to ${OUTFILE} with blocksize ${BS}"
# conf=fdatasync or oflag=direct ?
ionice -c2 -n7 dd if="${INFILE}" bs=${BS} conv=noerror,sync,notrunc oflag=direct status=progress of="${OUTFILE}" 
