#!/bin/bash
HOST=$(hostname)

CPU=$(egrep '^(vendor_id|Hardware)' /proc/cpuinfo  | cut -f2 -d: | sort -u | sed 's/.*\(Genuine\|Authentic\)//g; s/[[:space:]]\+//g;' | tr '[A-Z]' '[a-z]')
if [ -z "${CPU}" -a -n "$(command -v lscpu)" ]
then
	CPU=$(lscpu -y | grep -E 'Vendor' | cut -f2 -d: | sed 's/^[[:space:]]\+//g; s/[[:space:]]\+/_/g; s/.*\(Genuine\|Authentic\)//g; s/[[:space:]]\+//g;' | tr '[A-Z]' '[a-z]')
fi
CPU=${CPU:-unknown}

[[ -d "/proc/bus/pci" ]] && PCI="pci"
[[ -d "/proc/scsi" ]] && SCSI="scsi"
for i in cpu usb ${PCI} ${SCSI}
do
	if [ -n "$(which ls${i})" ]
	then
		file="${HOST}.${CPU}.${i}"
		eval "ls${i}" > "${file}"
	else
		echo "can't find tool: ls${i}"
	fi
done
if [ -n "$(which smartctl)" -a -r "${HOST}.${CPU}.scsi" ]
then
	for i in $(grep ATA "${HOST}.${CPU}.scsi" | sed 's/.*\/dev\///g;')
	do
		smartctl -a /dev/$i
	done > "${HOST}.${CPU}.smartctl"
fi

cat /proc/cpuinfo > "${HOST}.${CPU}.proccpu"

[[ -n "$(which dmidecode)" ]] && dmidecode > "${HOST}.${CPU}.dmi"


#egrep '^(vendor_id|model name|Hardware|Model)' /proc/cpuinfo | sort -fiu

#Hardware        : BCM2835
#model name      : ARMv6-compatible processor rev 7 (v6l)
#Model           : Raspberry Pi Model B Rev 1
#vendor_id	 : 

#Hardware        :
#model name      : Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
#Model           :
#vendor_id       : GenuineIntel

#Hardware        :
#model name      : AMD Ryzen 5 2600 Six-Core Processor
#Model           :
#vendor_id       : AuthenticAMD
