#!/bin/bash
WIDTH=100
COLUMNS=${COLUMNS:-$(tput cols)}

if [ $COLUMNS -gt ${WIDTH} ]
then
	scale=1
elif [ $COLUMNS -gt $(( $WIDTH / 2 )) ]
then
	scale=2
else
	scale=4
fi

now=$(cat /sys/class/power_supply/BAT0/charge_now)
full=$(cat /sys/class/power_supply/BAT0/charge_full)

BATP=$(echo "scale = 2; print ( $now / $full ) * 100" | bc)
BATP=$(echo "($BATP + .5) /1" | bc)
#echo battery=$BATP

PADL=$(( ($WIDTH / $scale) - ( (100 - $BATP) / $scale ) - 2))
PADR=$(( ($WIDTH / $scale) - $PADL - 1 ))

fcolor="\e[0m\e[100m"
if [ ${BATP} -gt 70 ]
then
	# green
	color="\e[0m\e[1m\e[92m"
	ecolor="\e[0m\e[42m"
elif [ ${BATP} -gt 40 ]
then
	# yellow
	color="\e[0m\e[1m\e[93m"
	ecolor="\e[0m\e[43m"
elif [ ${BATP} -gt 20 ]
then
	# magenta
	color="\e[0m\e[1m\e[91m"
	ecolor="\e[0m\e[1m\e[45m"
else
	# red
	color="\e[0m\e[1m\e[91m"
	ecolor="\e[0m\e[1m\e[101m"
fi

printf "%bE%${PADL}s%b%b%${PADR}s\e[0m\e[1mF\e[0m\n"  "${ecolor}"   " "   "${color}${BATP}"   "${fcolor}"    " "
