#!/bin/bash
# (c) 2021 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/uml2png
# 
PUML="https://example.com/plantuml"	#base URL for your plantuml instance
POSTURL="${PUML}/form"
#TLS="--insecure"        # this can be commented out if you trust the certs

############################
PROG="${0##*/}"
UMLFILE="$1"
UMLNAME="${UMLFILE%.*}"		# strip off the extension....

if [ -z "${UMLFILE}" ]
then
        echo "What UML file to convert?"
        exit 1
elif [ ! -r "${UMLFILE}" ]
then
        echo "Can't read UML data from file: ${UMLFILE}"
        exit 1
fi

urldata=$(perl -p -e 's/([^A-Za-z0-9])/sprintf("%%%02X", ord($1))/seg' ${UMLFILE})

URL=$(curl \
        --request POST \
        --referer ${PUML} \
        ${TLS} \
        --include \
        --data "text=${urldata}" \
        --data "submit=submit" \
        $POSTURL 2>&1 | grep "Location:" | awk '{print $2}')

URL=${URL//[^[:print:]]/}

if [ -z "${PROG##*png*}" ]
then
	PNG=${URL//\/uml\//\/png\/}
	curl --location --silent --output ${UMLNAME}.png ${PNG}

elif [ -z "${PROG##*svg*}" ]
then
	SVG=${URL//\/uml\//\/svg\/}
	curl --location --silent --output ${UMLNAME}.svg ${SVG}

elif [ -z "${PROG##*txt*}" ]
then
	TXT=${URL//\/uml\//\/txt\/}
	curl --location --silent ${TXT}
else
	echo "unknown/unsupported extension ${PROG//uml2/}"
fi
