#!/bin/bash

PUML="https://example.com/plantuml"	#base URL for your plantuml instance
POSTURL="${PUML}/form"
#TLS="--insecure"        # this can be commented out if you trust the certs

############################

UMLFILE="$1"

if [ -z "${UMLFILE}" ]
then
        echo "What UML file to convert?"
        exit 1
elif [ ! -r "${UMLFILE}" ]
then
        echo "Can't read UML data from file: ${UMLFILE}"
        exit 1
fi

urldata=$(perl -p -e 's/([^A-Za-z0-9])/sprintf("%%%02X", ord($1))/seg' ${UMLFILE})

URL=$(curl \
        --request POST \
        --referer ${PUML} \
        ${TLS} \
        --include \
        --data "text=${urldata}" \
        --data "submit=submit" \
        $POSTURL 2>&1 | grep "Location:" | awk '{print $2}')

PNG=${URL//\/uml\//\/png\/}

echo "${PNG}"
