#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/vid2mp4
# 
PROG="${0##*/}"

EXT2=${PROG//*2/}

if [ -z "$*" ]; then
  echo "${PROG} [filename]"
  echo " -- output is [filename.${EXT2}]"
  exit 1
fi

for vidfile in ${*}; 
do

  if [ -r "${vidfile}" ]; then
    out="${vidfile%.*}.${EXT2}"
  else
    echo "can't find/read '${vidfile}'"
    exit 1
  fi

  ffmpeg -i "${vidfile}" -y -map 0 -c:v copy -c:a copy -sn -movflags +faststart "${out}"  || \
  	ffmpeg -i "${vidfile}" -y -map 0 -c:v h264 -c:a aac -b:a 128k -sn -movflags +faststart "${out}"
done
