#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/xrdp
# 

# See if there's an xorg running
TD=$(ps -awwwx | grep -iE 'xorg.*displayfd' | grep -o 'vt[0-9]')
TD=${TD//vt/}
TD=${TD:-1}
TD=$((TD - 1))

DISPLAY=${DISPLAY:-:$TD}
PATH=${PATH}:/usr/sbin

PORT=$(lsof -i -n | grep x11vnc | cut -f 2 -d: | awk '{print $1}')
XAUTH=$(ps wwwwaux | grep -- -auth | sed 's/.*-auth//g' | grep -E 'var|run' | awk '{print $1}')
if [ -z "${XAUTH}" -a -n "$1" ]
then
	XAUTH=$1
fi
XAUTH="${XAUTH:+-auth $XAUTH}"

if [ -n "${PORT}" ]
then
	echo "already listening on port ${PORT}"
	exit
fi

# OPTS="-noxdamage -nowf|-nowcr -fixscreen -cursor most|arrow | -noxfixes"
OPTS="-speeds dsl -xwarppointer  -xinerama" #-threads 

x11vnc -q ${OPTS} -bg -notruecolor -overlay -nobell -nodragging ${XAUTH} -display ${DISPLAY}
# -progressive 100 -nap

if [ $LOCAL ];
then
  vncviewer -fullscreen -owncmap -depth 8 -encodings "tight" -compresslevel 9 -quality 0 localhost${DISPLAY}
fi

