#!/bin/bash

# 9018 sshd: username@pts/4
USERLIST=$(pgrep -fa "sshd:.*@" | awk '{print $3}' | cut -f1 -d@)

for USER in ${USERLIST}
do
	xauth merge ~${USER}/.Xauthority >/dev/null 2>&1
	if [ 0 -ne $? ]
	then
		xauth -f ~${USER}/.Xauthority list 2>&1 | while read line
		do
			xauth add $line
		done
	fi
done
