#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/zone-bin2text
# 

if [ -z "$*" ]
then
	echo "$0 [zone] [zonefile]"
	exit 1
fi

if [ -r "${2}" ]
then
	named-compilezone -f raw -F text -o - ${1} ${2}
else
	echo "$0 - error reading zonefile '${2}'"
	exit 1
fi

