#!/bin/bash
# (c) 2020 Leif Sawyer
# License: GPL 3.0 (see https://github.com/akhepcat/)
# Permanent home:  https://github.com/akhepcat/Miscellaneous/
# Direct download: https://raw.githubusercontent.com/akhepcat/Miscellaneous/master/zoom-upd
# 
ubuntu=0
redhat=0
unk=0

rzv=$(curl -A "Mozilla/5.0 (X11; Linux x86_64)" \
	--silent https://zoom.us/download | grep -E 'linux-ver-text.*Version' | sed 's/.*Version //; s|</span>.*||;' )

# expand the detection for different OS's as needed
if [ -n "$(which apt 2>/dev/null)" ]
then
	ubuntu=1
elif [ -n "$(which rpm 2>/dev/null)" ]
then
	redhat=1
elif [ -n "$(which pacman 2>/dev/null)" ]
then
	arch=1
else
	unk=1
fi


# expand the individual OS sections as needed
if [ 1 -eq ${ubuntu:-0} ]
then
	lzv=$(dpkg -l zoom 2>&1 | grep ^ii | awk '{print $3}')
	dpkg --compare-versions $lzv lt $rzv
	if [ $? -eq 0 ]
	then
		echo "Upgrade needed"
		wget -O /tmp/zoom-${rzv}-amd64.deb https://zoom.us/client/latest/zoom_amd64.deb
		sudo dpkg -i /tmp/zoom-${rzv}-amd64.deb
		rm -i /tmp/zoom-${rzv}-amd64.deb
	else
		echo "no newer version available"
	fi
elif [ 1 -eq ${redhat:-0} ]
then
	lzv=$(rpm -q zoom --info 2>&1 | grep Version | cut -f2 -d:)
	# need to compare current version vs remote version
	
	wget -O /tmp/zoom-${rzv}-x86_64.rpm https://zoom.us/client/latest/zoom_x86_64.rpm

	# because we might need dependencies
	sudo yum install /tmp/zoom-${rzv}-x86_64.rpm

	rm -i /tmp/zoom-${rzv}-x86_64.rpm
elif [ 1 -eq ${arch:-0} ]
then
	# Need to detect the current version
	# need to compare current version vs remote version
	
	wget -O /tmp/zoom-${rzv}-x86_64.pkg.tar.xz https://zoom.us/client/latest/zoom_x86_64.pkg.tar.xz

	# This grabs dependencies
	pacman -U /tmp/zoom-${rzv}-x86_64.pkg.tar.xz

	rm -i /tmp/zoom-${rzv}-x86_64.pkg.tar.xz
elif [ 1 -eq ${unk:-0} ]
then
	# Need to detect the current version
	# need to compare current version vs remote version
	
	wget -O /tmp/zoom-${rzv}-x86_64.tar.xz https://zoom.us/client/latest/zoom_x86_64.tar.xz
	echo "You'll need to manually install from the package"
else
	echo "Can't determine version for automatic upgrade"
fi
