#!/bin/bash

ubuntu=0
redhat=0
unk=0

if [ -n "$(which apt)" ]
then
	ubuntu=1
elif [ -n "$(which rpm)" ]
then
	redhat=1
else
	unk=1
fi

lzv=$(dpkg -l zoom | grep ^ii | awk '{print $3}')

rzv=$(curl -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36" \
	--silent https://zoom.us/download | grep -E 'linux-ver-text.*Version' | sed 's/.*Version //; s|</span>.*||;' )

echo "cur: ${lzv:-0}"
echo "rem: ${rzv:-0}"

dpkg --compare-versions $lzv lt $rzv && echo "upgrade needed"

if [ ${ubuntu:-0} ]
then
	wget -O /tmp/zoom-${rzv}-amd64.deb https://zoom.us/client/latest/zoom_amd64.deb
	sudo dpkg -i /tmp/zoom-${rzv}-amd64.deb
	rm -i /tmp/zoom-${rzv}-amd64.deb
elif [ ${redhat:-0} ]
then
	wget -O /tmp/zoom-${rzv}-x86_64.rpm https://zoom.us/client/latest/zoom_x86_64.rpm
	sudo rpm -Uvh /tmp/zoom-${rzv}-x86_64.rpm
	rm -i /tmp/zoom-${rzv}-x86_64.rpm
elif [ ${unk:-0} ]
then
	wget -O /tmp/zoom-${rzv}-x86_64.pkg.tar.xz https://zoom.us/client/latest/zoom_x86_64.pkg.tar.xz
	ls -alF /tmp/zoom-${rzv}-x86_64.pkg.tar.xz
else
	echo "Can't determine version for automatic upgrade"
fi
